include/tmp/directory.hpp, include/tmp/file.hpp, include/tmp/path.hpp, lib/path.cpp
Rewrite documentation for all classes and methods
=> Documentation

include/tmp/file, lib/file.cpp, tests/file_test.cpp
Implement tmp::file::read method, which returns the ifstream for the file
=> Add tmp::file::read method

.clang-format, .github/workflows/Lint.yml, src/tmp.cpp, tests/directory_test.cpp, tests/file_test.cpp
- Add clang-format config
- Add CI job for formatting
=> Formatting

.cmake-format, .github/workflows/Lint.yml, cmake/FindFilesystem.cmake, tests/CMakeLists.txt
- Add cmake-format configuration
- Add cmake-format CI action
=> Add cmake-format checks

cmake/FindFilesystem.cmake, cmake/FindGTest.cmake, tests/CMakeLists.txt
Add a FindGTest.cmake script that tries to find GTest on the system and, if unsuccessful, fetches it from GitHub
=> Try find gtest on the system before fetching it

.github/workflows/Tests.yml, CMakeLists.txt, cmake/FindGTest.cmake
- Remove TMP_TEST option
- Use BUILD_TESTING option
- Add output on failure in ctest
=> Use CTest's BUILD_TESTING option

tests/directory.cpp, tests/file.cpp
- Check for the type of created files
- Add tests for text files
=> More tests

src/tmp.cpp
- `file::copy` and `direcotory::copy` now throw proper exceptions
- Some internal tweaks
=> Tweak error reporting

src/tmp.cpp
This may need to be worked on some day later
=> Throw out of functions as soon as an error occurs

CMakeLists.txt
- Add homepage url to cmake lists
- Enable cpack generators
=> Enable CPack packaging

CMakeLists.txt, src/CMakeLists.txt, tests/CMakeLists.txt
=> Make this shared library

include/tmp/file, src/directory.cpp, src/file.cpp, src/utils.cpp, src/utils.hpp, tests/file.cpp
Also fix some mistakes from #104
=> Rename `suffix` to `extension`

.clang-tidy, include/tmp/entry, include/tmp/file, src/directory.cpp, src/entry.cpp, src/file.cpp, src/utils.cpp
=> Use clang-tidy's include cleaner

include/tmp/directory, include/tmp/entry, include/tmp/file, src/directory.cpp, src/entry.cpp, src/file.cpp, tests/directory.cpp, tests/file.cpp
- Add `std::hash` specializations for all classes
- Add relational operators for `tmp::entry`
- Add tests for these functions
=> Implement support functions

include/tmp/directory, include/tmp/entry, include/tmp/file, src/directory.cpp, src/entry.cpp, src/file.cpp, tests/file.cpp
Implement `input_stream` and `output_stream` getters for the `tmp::file`
=> Stream getters for `tmp::file`

.clang-tidy, include/tmp/file, src/entry.cpp, src/file.cpp
- To keep public headers clean
=> Remove all private constructors

.clang-tidy, .github/workflows/lint.yml, src/directory.cpp, tests/utils.hpp
Use `*.?pp` mask instead of `*.cpp`
=> Run linters on private headers

src/entry.cpp
Implement more generic `move` function with error reporting via `error_code&`
=> Refactor `tmp::entry::move` method

include/tmp/directory, src/directory.cpp
Add `directory::directory(std::error_code&)` and `directory::directory(std::string_view, std::error_code&)`
=> Add error-code constructors for `directory`

tests/directory.cpp, tests/file.cpp
Type traits, member types and input/output operations are now tested
=> Add more tests for `file`

src/file.cpp
Move out the common code for libstdc++ and libc++ implementations
=> Fix file handle closing in case of an error

meson.build, src/CMakeLists.txt, src/create.cpp
Use the recommended `_wfsopen` instead of the deprecated `_wfopen`
=> Use `wfsopen` on Windows

tests/file.cpp
The `tmp::file` constructor specifies that a file is created in the same file system as `std::temp_directory_path()`
=> Add a test that checks device for `file`s

LICENSE, include/tmp/directory, include/tmp/file, src/abi.hpp, src/directory.cpp, src/file.cpp, tests/directory.cpp, tests/file.cpp
The license should be included in all source files
=> Apply license to all sources properly
