bugdea1er/tmp

- include/tmp/file.hpp
- tests/file_test.cpp
- Remove unintuitive `operator<<`
- Make text and binary files distinctive
- Add write and append methods
Closes #1
> Implement tmp::file::write and tmp::file::append

- include/tmp/directory.hpp
- include/tmp/file.hpp
- include/tmp/path.hpp
- tmp::path constructor accepts an already created temp path
- tmp::file and tmp::directory create temp paths by themselves
Closes #7
> Implement error handling

- include/tmp/path.hpp
- lib/path.cpp
- tests/directory_test.cpp
- tests/file_test.cpp
Implement tmp::path::release, which releases the ownership of the managed path
> Implement tmp::path::release method

- include/tmp/path
- lib/path.cpp
- tests/directory_test.cpp
- tests/file_test.cpp
Add a tmp::path::move method which moves the managed path to the given target:
```cpp
/// Moves the managed path recursively to a given target, releasing
/// ownership of the managed path
/// @param to   A path to the target file or directory
/// @throws std::filesystem::filesystem_error if cannot move the owned path
void move(const std::filesystem::path& to);
```
> Add tmp::path::move

- README.md
- include/tmp/path
- lib/path.cpp
- tests/file_test.cpp
Make `tmp::path::move` to create the parent directories of the given target if they do not exist
> tmp::path::move creates parent directories

- lib/path.cpp
Fixed an issue where moving between devices would behave differently than on the same device:
- If moving between devices, fail if source is the file and target is a directory
- Remove the target recursively before copying over it
> Fix a bug with moving between devices

- include/tmp/file
- lib/file.cpp
- tests/file_test.cpp
Implement tmp::file::slurp method, which returns the entire contents for the file in a form of a string
> Add tmp::file::slurp method

- include/tmp/directory
- include/tmp/file
- include/tmp/path
- src/tmp.cpp
- tests/directory_test.cpp
- tests/file_test.cpp
Specify an alias for the filesystem namespace so that you can later replace it with compatible libraries
> Explicitly define used filesystem library

- include/tmp/directory
- include/tmp/file
- include/tmp/fs
- include/tmp/path
- src/tmp.cpp
Follow the "one file per top-level definition" style guide
- Move tmp::fs definition to a separate file
- Remove <filesystem> include
> Move tmp::fs definition to a separate file

- include/tmp/file
- src/tmp.cpp
- tests/file_test.cpp
- Remove `file::read` method
- Rename `file::slurp` method to `file::read`
> Unify read and slurp methods

- include/tmp/directory
- include/tmp/file
- src/tmp.cpp
- tests/file.cpp
The implicit operator is not always suitable, so there should be an explicit getter for the path
It is not possible to do this with a `class path` method because it conflicts with the class constructor
> Add explicit path getter method

- .github/workflows/Tests.yml
- Remove deprecated `macos@11`
- Use the new `macos@14`
- Replace `ubuntu@22.04` with `ubuntu@24.04`
> Use new runners

- include/tmp/path
- src/tmp.cpp
- tests/directory.cpp
- tests/file.cpp
- Mark `path::operator->` as deprecated
- Remove its usages
> Deprecate path::operator->

- .clang-tidy
- include/tmp/file
- include/tmp/path
- src/tmp.cpp
- tests/file.cpp
- Add `native_handle_type` to temporary files
- Add `file::native_handle` method
- Save the native handle
- Close the file on destruction, releasing or moving
> Close file descriptors of created files

- include/tmp/directory
- include/tmp/file
- src/directory.cpp
- src/file.cpp
- src/utils.cpp
- src/utils.hpp
- tests/directory.cpp
- tests/file.cpp
Constructors now throw `std::invalid_argument` when the `label` or `extension` arguments have invalid values
> Validate labels and extensions for temporary entries

- include/tmp/entry
- include/tmp/file
Mark `tmp::entry::release` and private `tmp::file` constructors as `NO_EXPORT`
> Do not export private methods

- include/tmp/directory
- include/tmp/entry
- include/tmp/file
- src/directory.cpp
- src/entry.cpp
- src/file.cpp
- tests/directory.cpp
- tests/file.cpp
- tests/utils.hpp
`tmp::entry` now owns a native handle to the opened resource and closes it when the path is deleted
> Open temporary directories

- include/tmp/directory
- include/tmp/entry
- include/tmp/file
- src/entry.cpp
- Make relational operators members of `tmp::entry` as in `std::directory_entry`
- Do not use `auto` in deleted constructors
- Use Named Requirements terminology in docs
> Tidy up operators declaration

- src/entry.cpp
- tests/directory.cpp
- tests/file.cpp
- Explicitly assign invalid value to `other` in move constructor and operator
- Check that moved-out entry does not close the moved-in entry
> Fix move semantics for `tmp::entry`

- .github/workflows/tests.yml
- src/CMakeLists.txt
Set flags like `-Werror` and `/WX` in CI and not in local builds
> Set WARNING_AS_ERROR in CI

- include/tmp/file
- src/file.cpp
It's not that necessary and takes up 10 lines in public headers
> Remove a private file constructor

- include/tmp/directory
- include/tmp/entry
- src/directory.cpp
- src/entry.cpp
- To keep public headers clean
- To provide a more convinient entry constructor from a pair
> Delete directory private constructor

- .github/workflows/tests.yml
- macos 12 is now deprecated:
(https://github.com/actions/runner-images/issues/10721)
- macos 15 is now available:
(https://github.com/actions/runner-images/issues/10686)
> Update used macos images

- .github/workflows/tests.yml
Apparently, Ubuntu images in Github Actions do not have `/tmp` in `tmpfs` and `TMPDIR` is not set
> Set up `tmpfs` on Linux systems

- src/CMakeLists.txt
- tests/CMakeLists.txt
According to [CMake documentation](https://cmake.org/cmake/help/latest/prop_tgt/UNITY_BUILD.html#prop_tgt:UNITY_BUILD), UNITY_BUILD property should not be set by the project
> Do not use unity build

- include/tmp/entry
- src/entry.cpp
- tests/CMakeLists.txt
- tests/directory.cpp
- tests/entry.cpp
- tests/file.cpp
- Fix a bug when moving an entry to itself caused a deletion of said entry
- Fix a bug when moving a directory to an existing file between filesystems would not throw an exception
- Fix a bug when move was constrained to regular files and directories only
- Fix a bug when an entry could be deleted even if it was not moved due to an error
- Add a lot of tests
- Explain the `entry::move` behaviour somewhat better
> Fix `tmp::entry::move` method

- src/directory.cpp
- src/file.cpp
Since we are using a GUID that is guaranteed not to overlap on the same machine, there is no point in checking if we have hit an existing file when trying to create a new one
> Do not try to create entry again if failed

- src/entry.cpp
I forgot that `INVALID_HANDLE_VALUE` exists on Windows
> Use a proper value for `invalid_handle`

- src/file.cpp
- tests/file.cpp
Also add more tests for text translation (LF to CRLF) on Windows
> Fix a bug when a text was written to a file in binary format on Windows

- include/tmp/file
- src/file.cpp
- tests/file.cpp
Methods `file::read`, `file::write` and `file::append` did not report errors due to use of `<fstream>` C++ API
Reimplement these methods via system calls to actually check for system errors and throw proper `std::filesystem::filesystem_error`
> Report errors in `file` input/output operations

- include/tmp/directory
- include/tmp/entry
- include/tmp/file
- src/directory.cpp
- src/entry.cpp
- src/file.cpp
Add overloads with `std::error_code&` for error reporting for:
- `entry::move`
- `directory::list`
- `file::read`
- `file::write`
- `file::append`
> Add `error_code` overloads for observers and modifiers

- .clang-tidy
- include/tmp/file
- src/file.cpp
- tests/file.cpp
Unlike `std::filesystem::file_size`, does not require existing path for the file
> Add `file::size` method

- include/tmp/directory
- include/tmp/entry
- include/tmp/file
- src/directory.cpp
- src/entry.cpp
- src/file.cpp
Explicitly inherit hash `operator()` from `tmp::entry`
Breaks ABI, so will be included in future versions
> Inherit hash from `tmp::entry`

- include/tmp/entry
- include/tmp/file
- src/create.cpp
- src/create.hpp
- src/entry.cpp
- src/file.cpp
- tests/checks.hpp
- tests/directory.cpp
- tests/entry.cpp
- tests/file.cpp
This essentially reverts https://github.com/bugdea1er/tmp/pull/114
Opening temporary directories doesn't help at all, since there is not much to do with its native handle, and even traversing the directory using the OS's native API reopens the directory
Also, defining and managing `native_handle` in `entry` limits the variety of types of handles: for instance, `file` could use corecrt on Windows and manage `int` instead of `HANDLE`
> Do not open temporary directories

- include/tmp/entry
- src/entry.cpp
- tests/entry.cpp
This mimics the `std::filesystem::rename` closer
> Do not create target parent when moving a temporary entry

- include/tmp/directory
- include/tmp/entry
- include/tmp/file
- src/CMakeLists.txt
- src/directory.cpp
- src/entry.cpp
- src/file.cpp
- src/move.cpp
- src/move.hpp
- tests/directory.cpp
- tests/entry.cpp
- tests/file.cpp
Abstract `tmp::entry` should not provide a `move` method because:
- the temporary entry may need to be closed before moving
- moving the temporary entry may not make sense at all, e.g. for sockets
> Move `move` from `entry`

- src/create.cpp
- src/create.hpp
- src/file.cpp
Follow up pull requests will accept `openmode` in `file` constructors
> Make `create` accept `openmode` as a parameter

- include/tmp/directory
- include/tmp/entry
- include/tmp/file
- src/directory.cpp
- src/entry.cpp
- src/file.cpp
I only needed that for tidier code in `file` input/output operations
> Remove all `error_code` overloads

- include/tmp/file
- src/file.cpp
Instead of proving a bunch of overloads for `file`, `file::text` and `file::copy`, provide a way to specify the openmode for the client
This mode will be used for opening a `std::filebuf`
> Add `openmode` parameter for file creation

- include/tmp/file
- src/file.cpp
- tests/file.cpp
Like in `std::fstream`, the `file::rdbuf` method hides the non-virtual method `std::basic_ios::rdbuf` to allow users to obtain a pointer to a stream buffer of type `std::filebuf` without using dynamic casts
This also allows users to get a C++26 `native_handle`:
```cpp
tmp::file().rdbuf()->native_handle()
```
> Add `file::rdbuf` method

- include/tmp/file
- tests/file.cpp
Add member type `native_handle_type` and member function `native_handle` to `file`, which was added to `std::basic_fstream` in [P1759R6](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p1759r6.html)
> Add `file::native_handle`

- include/tmp/file
- include/tmp/filebuf
- src/CMakeLists.txt
- src/create.cpp
- src/create.hpp
- src/file.cpp
- src/filebuf.cpp
Closes #160
This is a very hacky way to open a native handle in the three main C++ standard library implementations
I really don't want to implement filebuf myself
> Implement a custom `filebuf` for opening a native handle

- include/tmp/file
- src/create.cpp
- tests/file.cpp
Closes #166
A temporary file now always adds `std::ios::in | std::ios::out` to its open flags
In light of https://github.com/bugdea1er/tmp/issues/165 there is no point in opening a temporary file without the `std::ios::in` or `std::ios::out` flag, since otherwise it will be impossible to fill it or read its contents
Also fixed an error where an exception was not thrown if failed to open a filebuf
> Always open `file` with `in` and `out` flags

- src/create.cpp
- tests/file.cpp
For some `std::ios::openmode` flags, the resulting mode string was `nullptr` and was not checked before calling `fopen`
> Fixed a bug where invalid open mode was not handled correctly.

- include/tmp/directory
- src/create.cpp
- src/create.hpp
- src/directory.cpp
- src/move.cpp
- tests/CMakeLists.txt
- tests/directory.cpp
- tests/meson.build
The `string_view` argument to the `directory` constructor no longer serves as a parent name to the temporary directory; instead, it is now used as a prefix to the directory name
This is done because:
- This is closer to the `mktemp` documentation examples, which create `tmp.XXXXXX` paths rather than `tmp/XXXXXX`
- If one user program created a directory with a parent `label`, then another user program would sometimes fail to create a directory with the same label
Also, the parent directory for temporary directories is no longer forced to be created. The C++ standard requires `std::filesystem::temp_directory_path()` to return an existing directory; if it is deleted after getting the path and before creating our directory, we choose to fail as soon as possible
> Replace directory labels with prefixes

- include/tmp/file
- include/tmp/filebuf
- src/create.cpp
- src/file.cpp
- src/filebuf.cpp
- tests/file.cpp
When opening `tmp::filebuf`, simply save the open handle, which can be used to get a native handle
> Implement `file::native_handle` for C++17

- include/tmp/file
- src/file.cpp
- tests/file.cpp
`file` (which extends `std::iostream`) still provides `rdbuf() -> std::streambuf` which can be used for lower level I/O
`std::filebuf` (and `tmp::filebuf`) only provides `open`, `is_open` and `close` methods:
- `open` - we don't want the user to be able to reopen another file from the temporary file
- `close` - we don't want `file` to exist in a closed state
- `is_open` - will only return `false` for relocated `file` objects
> Breaking: Remove `file::rdbuf`

- include/tmp/file
- src/file.cpp
- tests/file.cpp
This is the next step to removing the `path()` method of the temporary file (https://github.com/bugdea1er/tmp/issues/165): we now can create a temporary copy without using the copy result path
> Do not use `file::path()` in `file::copy`

- src/file.cpp
- tests/file.cpp
This is the next step to removing the path() method of the temporary file (https://github.com/bugdea1er/tmp/issues/165): now we can move a temporary file without using its path
Technically, it always copies the file at this point, since I couldn't figure out how to hardlink a file without hardlinks
> Do not use `file::path()` in `file::move`

- include/tmp/file
- src/create.cpp
- src/create.hpp
- src/file.cpp
- tests/directory.cpp
- tests/file.cpp
This pr makes removes `file` inheritance from `entry` and removes file's access to its path.
- On POSIX systems, the path is unlinked immediately after file creation
- On Windows, the flag "delete on close" is used
This replicates implementations of C `std::tmpfile`
> Breaking: Remove `file::path()` method

- src/create.cpp
- src/create.hpp
- src/file.cpp
Implement two different `create_file` functions for POSIX and Windows
> Remove `open_native_handle`

- src/create.cpp
- tests/directory.cpp
After this, directory names will look nicer: `com.github.bugdea1er.tmp.yotR2k` instead of `com.github.bugdea1er.tmpyotR2k`
> Add a period to prefix if it's not empty

- src/create.cpp
To avoid race condition, we can first try to open the file using `O_TMPFILE` on Linux systems
> Use `O_TMPFILE` on Linux

- src/create.cpp
`T` is recommended for temporary files on Windows as mentioned here:   
https://learn.microsoft.com/en-us/archive/blogs/larryosterman/its-only-temporary
> Use T for temporary files openmode on Windows

- include/tmp/file
- src/file.cpp
- tests/file.cpp
On Unix systems, we can reliably use `/dev/fd/n` path for getting a path to an opened file
> Implement `file::path()`

- include/tmp/directory
- src/create.cpp
- src/create.hpp
- tests/directory.cpp
Since the `directory::directory(std::string_view)` parameter is no longer used as the parent directory name, the names `.` and `..` are no longer disallowed
This means that we can only check the directory separator in the native format of the prefix
> Simplify requirements to directory prefixes

- include/tmp/directory
- src/directory.cpp
Since Windows can actually prevent open directories from being deleted, and some Linux systems clean up `$TMPDIR` based on advisory BSD locks, the reserved memory is likely to be used to store the handle in the future
> Reserve some bytes in `directory`

- src/create.cpp
- src/create.hpp
Removed the "public" declaration of the `create_file` and `create_directory` overloads with `std::error_code`
> Hide `create_directory` function overload with `ec`

- src/create.cpp
Remove the `create_file(std::error_code&)` overload
> Refactor `create_file` for posix

- src/create.cpp
And tidy up internal functions
> Remove the `create_directory`(std::error_code&) overload

- src/directory.cpp
Underlying implementation of `directory::copy` now opens a `directory_iterator` on the `from` path to avoid TOC/TOU vulnerability
> Fix TOC/TOU in `directory::copy`

- meson.build
- src/CMakeLists.txt
- src/abi.hpp
Apparently you can always specify `dllexport` for library classes on Windows, so this pull request eliminates the need to add the `TMP_BUILDING_DLL` compilation definition
> Always set `__declspec(dllexport)` for classes

- src/file.cpp
Added file type check to `open_file`, required for using `copyfile` in #194
> Check that `open_file` opens a regular file

- src/file.cpp
- tests/file.cpp
Optimize file copying by adding platform-specific implementations for the `file::copy` function
- Introduces `copy_file` implementations using `copyfile` (for macOS) and `sendfile` (for Linux) when available
- Falls back to a buffered copy implementation if neither API is available
> Optimize `file::copy`

- include/tmp/file
- src/file.cpp
- tests/file.cpp
Add a flush call at the beginning of `file::move`
> Flush buffered input in `file::move`

- .clang-tidy
- src/directory.cpp
The standard does not specify that only `bad_alloc` can be thrown from `remove_all`
> Catch all exceptions in `~directory`

- .clang-tidy
- include/tmp/directory
- src/directory.cpp
- tests/directory.cpp
According to the C++ standard:
> When a call by the implementation to an operating system or other underlying API results in an error that prevents the function from meeting its specifications, an exception of type `filesystem_error` shall be thrown. For functions with a single path argument, that argument shall be passed to the `filesystem_error` constructor with a single path argument...
This fixes the exception thrown by `directory::copy` and adds tests for it
> Fix exceptions thrown from `directory::copy`

- src/file.cpp
Eliminate the need to close the file manually in `file::copy`
> Implement `file_handle` for auto-closing an open file

- .clang-tidy
- src/create.cpp
`open` with `O_TMPFILE` requires an existing directory to create an unnamed file
> Fix creating a file with `O_TMPFILE`

- src/create.cpp
- tests/file.cpp
Instead of dealing with signals, file permissions and such, delegate it to `std::tmpfile`
After creating the file, we can simply `std::freopen` the file with the desired `openmode`
Part of https://github.com/bugdea1er/tmp/issues/193 for Windows
> Use `std::tmpfile` in `create_file` on Windows

- src/file.cpp
> Refactor `create_file`

- .github/workflows/windows.yml
- include/tmp/file
- tests/file.cpp
Implemented `basic_file` template instead of `file` class
Closes #195
> Implement `tmp::basic_file`

- include/tmp/directory
- include/tmp/file
- src/abi.hpp
- src/directory.cpp
- src/file.cpp
Functions used in the inline function bodies should not be used by end users
> Move private declarations to `namespace detail`
